apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-spring-boot-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-spring-boot-app
  template:
    metadata:
      labels:
        app: my-spring-boot-app
    spec:
      containers:
      - name: my-spring-boot-app
        image: 992293216837.dkr.ecr.ap-south-1.amazonaws.com/study/demo-repo:latest
        ports:
        - containerPort: 8080
          name: http

