name: Compile Java Application
on: 
    - workflow_dispatch
    - push
permissions:
      id-token: write
      contents: read
env:
    EKS_CLUSTER_NAME: 'demo-eks-cluster'

jobs:
    Build-Application:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Setup Java
              uses: actions/setup-java@v4
              with:
                distribution: 'temurin'
                java-version: '17'
                cache: maven

            - name: Build Application
              run:  mvn clean install

            - name: Upload Artifact
              uses: actions/upload-artifact@v4
              with:
                name: java-build-artifact
                path: target/*.jar

            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                audience: sts.amazonaws.com
                aws-region: ap-south-1
                role-to-assume: arn:aws:iam::992293216837:role/github-action-oidc-Role-xta7NbBBHjdI
           
            - name: Login to Amazon ECR
              id: login-ecr
              uses: aws-actions/amazon-ecr-login@v1
              with:
                mask-password: true

            - name: Build, tag, and push docker image to Amazon ECR
              env:
                REGISTRY: ${{ steps.login-ecr.outputs.registry }}
                REPOSITORY: study/demo-repo
                IMAGE_TAG: ${{ github.run_id }}
              run: |
                echo ${{ github.run_id }}
                docker build -t $REGISTRY/$REPOSITORY .
                docker push $REGISTRY/$REPOSITORY
                docker tag $REGISTRY/$REPOSITORY $REGISTRY/$REPOSITORY:$IMAGE_TAG
                docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG


            #   If You want to use DockerHub use below code.
            #   =============================================
            # - name: Docker Login
            #   uses: docker/login-action@v3
            #   with:
            #     username: ${{ vars.DOCKERHUB_USERNAME }}
            #     password: ${{ secrets.DOCKERHUB_TOKEN }}
            # - name: Enable QEMU
            #   uses: docker/setup-qemu-action@v3
        
            # - name: Set up Docker Buildx
            #   uses: docker/setup-buildx-action@v3
        
            # - name: Build and Push Docker Images with Retry
            #   uses: docker/build-push-action@v6
            #   with:
            #     context: .
            #     file: Dockerfile
            #     tags: waghangad/spring-java-eks:latest
            #     push: true
            #     platforms: linux/amd64,linux/arm64

    Deploy-Application:
        needs: Build-Application
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Install kubectl
              uses: azure/setup-kubectl@v4

            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                audience: sts.amazonaws.com
                aws-region: ap-south-1
                role-to-assume: arn:aws:iam::992293216837:role/github-action-oidc-Role-xta7NbBBHjdI
          
            - name: Update kubeconfig for EKS
              run: aws eks update-kubeconfig --name ${{ env.EKS_CLUSTER_NAME }}

            - name: Run k8s command
              run: |
                # kubectl create -f service.yml
                # kubectl create -f deployment.yml
                kubectl set image deployment/my-spring-boot-app my-spring-boot-app=992293216837.dkr.ecr.ap-south-1.amazonaws.com/study/demo-repo:latest